name: Test radian

on:
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RADIAN_NO_INPUTHOOK: 1

jobs:
  pytest:
    name: ${{ matrix.os }} r-${{ matrix.r }} py-${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        r: [latest]
        python: [3.12]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ matrix.python }}
      - name: Install rchitect
        run: python -m pip install -e .[dev]
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - name: Install libpng-dev
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libpng-dev          
      - name: Install reticulate and askpass
        run: Rscript -e "install.packages(c('reticulate', 'askpass'))"
      - name: Install radian and run tests
        shell: bash
        run: |
          git clone https://github.com/randy3k/radian
          cd radian
          python -m pip install -e .[test]
          python -m pip install jedi
          pytest -s
